spring:
  datasource:
    url: jdbc:mysql://localhost:3306/swiggatodb?createTableIfNoExists=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: ravirajaccio@gmail.com
    password: aoenohpkslziacfo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 4444
